[package]
name = "regex-bench"
version = "0.1.0"
authors = ["devsnek", "Jonah Snider <jonah@jonah.pw> (https://jonah.pw)"]
edition = "2018"

publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
